# Generated by Django 4.0.6 on 2022-07-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banco", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ultima_movimentacao", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="banco.cliente"
                    ),
                ),
                ("extrato_conta", models.ManyToManyField(to="banco.conta")),
                ("extrato_deposito", models.ManyToManyField(to="banco.deposito")),
                ("extrato_saque", models.ManyToManyField(to="banco.saque")),
                (
                    "extrato_transferencia",
                    models.ManyToManyField(to="banco.transferencia"),
                ),
            ],
        ),
    ]
